name: "Process issues Events"

on:
  issues:
    types:
      - assigned
      - closed
      - edited
      - opened
      - labeled

jobs:
  community_check:
    name: "Community Check"
    uses: ./.github/workflows/community-check.yml
    secrets: inherit
    with:
      # This is a ternary that sets the variable to the assigned user's login on assigned events,
      # and otherwise sets it to the username of the pull request's author. For more information:
      # https://docs.github.com/en/actions/learn-github-actions/expressions#example
      username: ${{ github.event.action == 'assigned' && github.event.assignee.login || github.event.issue.user.login }}

  automation_labeler:
    name: "Automation Labeler"
    needs: community_check
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ github.event.issue.html_url }}
    steps:
      - name: "Generate Token"
        id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: "Add needs-triage for non-maintainer"
        if: github.event.action == 'opened' && needs.community_check.outputs.maintainer == 'false'
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: gh issue edit ${{ env.ISSUE_URL }} --add-label needs-triage

      - name: "Add prioritized when assigned to maintainers"
        if: github.event.action == 'assigned' && needs.community_check.outputs.maintainer == 'true'
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: gh issue edit ${{ env.ISSUE_URL }} --add-label prioritized

      - name: "Add prioritized to regressions"
        if: github.event.label.name == 'regression'
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: gh issue edit ${{ env.ISSUE_URL }} --add-label prioritized

      - name: "Remove unnecessary labels on closure"
        if: github.event.action == 'closed'
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: gh issue edit ${{ env.ISSUE_URL }} --remove-label needs-triage,waiting-response

  service_labeler:
    name: "Service Labeler"
    if: contains(fromJSON('["opened", "edited"]'), github.event.action)
    runs-on: ubuntu-latest
    steps:
      - name: "Apply Labels"
        uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler-issue-triage.yml
          enable-versioned-regex: 0
          include-title: 1

  community_note:
    name: "Add Community Note"
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: "Add community note to new Issues"
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            # Community Note

            **Voting for Prioritization**

            * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original post to help the community and maintainers prioritize this request.
            * Please see our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) for information on how we prioritize.
            * Please **do not** leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.

            **Volunteering to Work on This Issue**

            * If you are interested in working on this issue, please leave a comment.
            * If this would be your first contribution, please review the [contribution guide](https://hashicorp.github.io/terraform-provider-aws/).

  closed_issue_comment:
    name: "Closed Issue Comment"
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: "Add comment on closed issues"
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            > [!WARNING]
            > This issue has been closed, meaning that any additional comments are hard for our team to see. Please assume that the maintainers will not see them.
            >
            > Ongoing conversations amongst community members are welcome, however, the issue will be locked after 30 days. Moving conversations to another venue, such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33), is recommended. If you have additional concerns, please open a new issue, referencing this one where needed.
