name: team-slack-bot

on:
  schedule:
    - cron: '0 15 * * 1-5'

jobs:
  open-pr-stats:
    runs-on: ubuntu-latest
    name: open-pr-stats
    if: github.repository_owner == 'hashicorp'
    steps:
      - uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1.10.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
      - name: open-pr-stats
        uses: breathingdust/github-team-slackbot@8f1053f9b472b94e6564ebc499a92136c48ace1f # v18.5.1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          team_slug: terraform-aws
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack_channel: ${{ secrets.SLACK_CHANNEL }}
